name: juice-shop-ci-develop
on:
  push:
    branches:
      - develop

permissions:
  contents: read
  security-events: write

env:
  REGISTRY: ghcr.io
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  trivy-fs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@v0.36.0 
        with:
          scan-type: fs
          scan-ref: .
          format: "sarif"
          output: "trivy-fs-results.sarif"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          exit-code: "0"

      - name: Upload Trivy FS SARIF report to Github Security
        uses: github/codeql-action/upload-sarif@v3 
        if: always()
        with:
          sarif_file: trivy-fs-results.sarif
          category: trivy-fs

      - name: upload Trivy FS results to S3
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp trivy-fs-results.sarif s3://${{ secrets.S3_BUCKET_NAME }}/trivy-fs/$(date +%Y-%m-%d)/${{ github.sha }}.sarif

  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci

      - name: npm-audit report
        run: npm audit --json > npm-audit-results.json || true

      - name: Upload npm audit report to s3
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp npm-audit-results.json s3://${{ secrets.S3_BUCKET_NAME }}/sca/$(date +%Y-%m-%d)/${{ github.sha }}.json

  build-lint-test:
    runs-on: ubuntu-latest
    needs: [trivy-fs, sca]
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "22"
      - name: cache npm
        uses: actions/cache@v5.0.5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Unit tests
        run: npm test
      - name: API tests
        run: npm run test:api
      - name: Build frontend
        run: npm run build:frontend
      - name: Build server
        run: npm run build:server

  container-scan-push:
    runs-on: ubuntu-latest
    needs: [trivy-fs, sca, build-lint-test]
    outputs:
      image-tag: ${{ steps.tag.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.1.0
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4.2.0 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase repository name
        id: repo
        run: echo "name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      
      - name: Short SHA
        id: tag
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v6.1.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=sha,format=long
            type=ref,event=branch

      - name: Build Docker 
        uses: docker/build-push-action@v7.2.0
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:sha-${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:sha-${{ github.sha }}
          format: sarif
          output: trivy-container-results.sarif
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          vuln-type: "os,library"

      - name: Upload Trivy image scan SARIF report to Github Security
        uses: github/codeql-action/upload-sarif@v3 
        if: always()
        with:
          sarif_file: trivy-container-results.sarif
          category: trivy-container

      - name: Upload Trivy container scan results to s3
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          aws s3 cp trivy-container-results.sarif s3://${{ secrets.S3_BUCKET_NAME }}/trivy-image/$(date +%Y-%m-%d)/${{ github.sha }}.sarif

      - name: Push Docker Image
        uses: docker/build-push-action@v7.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-develop:
    runs-on: ubuntu-latest
    needs: container-scan-push
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          repository: Knightcrawlerr/eks-secobs
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: eks-secobs

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Update helm values file with new image tag for development deployment
        run: |
          cd eks-secobs
          sed -i "s|tag: .*|tag: \"sha-${{ github.sha }}\"|g" apps/juice-shop/values-dev.yaml
          git add apps/juice-shop/values-dev.yaml
          git diff --cached --quiet || git commit -m "ci: juice-shop prod → sha-${{ needs.container-scan-push.outputs.image-tag }} [skip ci]"
          git push origin HEAD:develop
