name: juice-shop-ci-main
on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set Short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (main)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/juice-shop:latest,${{ secrets.DOCKER_HUB_USERNAME }}/juice-shop:prod-${{ steps.vars.outputs.SHORT_SHA }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/juice-shop:prod-${{ steps.vars.outputs.SHORT_SHA }}
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/juice-shop:prod-${{ steps.vars.outputs.SHORT_SHA }},mode=max

  updateK8s:
    runs-on: ubuntu-latest
    needs: docker-build 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: Knightcrawlerr/eks-secobs
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: eks-secobs
      - name: Update Juice Shop image in Kubernetes deployment
        run: |
          cd eks-secobs
          sed -i "s|tag: .*|tag: \"prod-${{ needs.docker-build.outputs.SHORT_SHA }}\"|g" apps/juice-shop/values-prod.yaml
         
      - name: Commit and push changes
        run: |
          cd eks-secobs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add apps/juice-shop/values-prod.yaml
          git commit -m "[CI]: Updated Juice Shop image to ${{ needs.docker-build.outputs.SHORT_SHA }}"
          git push origin main




          