name: juice-shop-ci-pr
on:
  pull_request:
    branches:
      - main

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run API tests
        run: npm run test:api

      - name: Run lint
        run: npm run lint

      - name: Build frontend
        run: npm run build:frontend

      - name: Build server
        run: npm run build:server

  docker-build:
    runs-on: ubuntu-latest
    needs: build-lint-test
    outputs:
      SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set Short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/juice-shop:latest,${{ secrets.DOCKER_HUB_USERNAME }}/juice-shop:prod-${{ steps.vars.outputs.SHORT_SHA }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/juice-shop:prod-${{ steps.vars.outputs.SHORT_SHA }}
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/juice-shop:pr-${{ steps.vars.outputs.SHORT_SHA }},mode=max