name: juice-shop-ci
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

      - name: Run API tests
        run: npm run test:api

      - name: Build frontend
        run: npm run build:frontend

      - name: Build server
        run: npm run build:server

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    outputs:
      SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set Short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (main)
        if: github.ref_name == 'main' || github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/juice-shop:latest,${{ secrets.DOCKER_HUB_USERNAME }}/juice-shop:prod-${{ steps.vars.outputs.SHORT_SHA }}

      - name: Build and push Docker image (non-main)
        if: github.ref_name != 'main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/juice-shop:${{ github.ref_name }}-${{ steps.vars.outputs.SHORT_SHA }}
  updateK8s:
    runs-on: ubuntu-latest
    needs: docker-build 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: Knightcrawlerr/eks-secobs
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: eks-secobs
      - name: Update Juice Shop image in Kubernetes deployment
        run: |
          cd eks-secobs
          if [ "${{ github.ref_name }}" == "main" ]; then
            sed -i "s|tag: .*|tag: \"${{ github.ref_name }}-${{ needs.docker-build.outputs.SHORT_SHA }}\"|g" apps/juice-shop/values-prod.yaml
          else
            sed -i "s|tag: .*|tag: \"${{ github.ref_name }}-${{ needs.docker-build.outputs.SHORT_SHA }}\"|g" apps/juice-shop/values-dev.yaml
          fi
      - name: Commit and push changes
        run: |
          cd eks-secobs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ "${{ github.ref_name }}" == "main" ]; then
            git add apps/juice-shop/values-prod.yaml
            git commit -m "[CI]: Updated Juice Shop image to ${{ needs.docker-build.outputs.SHORT_SHA }}"
          else
            git add apps/juice-shop/values-dev.yaml
            git commit -m "[CI]: Updated Juice Shop image to ${{ needs.docker-build.outputs.SHORT_SHA }}"
          fi
          git push origin main




          